[build]
# Menggunakan builder default (Nixpacks)

[deploy]
# Biarkan Railway mendeteksi start command secara otomatis (npm start)
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services]
# Memaksa Railway mengarahkan trafik domain ke port internal 3000
# Sesuai dengan default PORT di server.js jika env.PORT tidak ada
tcp.port = 3000

[[services.healthChecks]]
path = "/"
interval = 10
timeout = 5
successThreshold = 1
failureThreshold = 3
